package edu.lcu.masterfollies.domain;

import edu.lcu.masterfollies.domain.ClubNames;
import edu.lcu.masterfollies.domain.ClubNamesExample;
import java.util.List;
<<<<<<< HEAD
import java.util.Map;

=======
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
import org.apache.ibatis.annotations.Param;

public interface ClubNamesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int countByExample(ClubNamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int deleteByExample(ClubNamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int insert(ClubNames record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int insertSelective(ClubNames record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    List<ClubNames> selectByExample(ClubNamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    ClubNames selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int updateByExampleSelective(@Param("record") ClubNames record, @Param("example") ClubNamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int updateByExample(@Param("record") ClubNames record, @Param("example") ClubNamesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int updateByPrimaryKeySelective(ClubNames record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_names
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int updateByPrimaryKey(ClubNames record);
<<<<<<< HEAD
    
    List<Map<String,Object>> selectClubListandRankByJudgeID(@Param("judge_id") Integer judgeId,@Param("girl") Boolean girl);
=======
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
}