package edu.lcu.masterfollies.domain;

public class ClubNames {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_names.id
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_names.club_name
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    private String clubName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_names.girl
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    private Boolean girl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_names.contact
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_names.club_order
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    private Integer clubOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_names.id
     *
     * @return the value of club_names.id
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_names.id
     *
     * @param id the value for club_names.id
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_names.club_name
     *
     * @return the value of club_names.club_name
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public String getClubName() {
        return clubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_names.club_name
     *
     * @param clubName the value for club_names.club_name
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public void setClubName(String clubName) {
        this.clubName = clubName == null ? null : clubName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_names.girl
     *
     * @return the value of club_names.girl
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public Boolean getGirl() {
        return girl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_names.girl
     *
     * @param girl the value for club_names.girl
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public void setGirl(Boolean girl) {
        this.girl = girl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_names.contact
     *
     * @return the value of club_names.contact
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_names.contact
     *
     * @param contact the value for club_names.contact
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_names.club_order
     *
     * @return the value of club_names.club_order
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public Integer getClubOrder() {
        return clubOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_names.club_order
     *
     * @param clubOrder the value for club_names.club_order
     *
     * @mbggenerated Thu Feb 21 14:05:58 CST 2013
     */
    public void setClubOrder(Integer clubOrder) {
        this.clubOrder = clubOrder;
    }
}