package edu.lcu.masterfollies.domain;

public class ListShowOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_show_order.id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_show_order.club_id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    private Integer clubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_show_order.order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    private Integer order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_show_order.id
     *
     * @return the value of list_show_order.id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_show_order.id
     *
     * @param id the value for list_show_order.id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_show_order.club_id
     *
     * @return the value of list_show_order.club_id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_show_order.club_id
     *
     * @param clubId the value for list_show_order.club_id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_show_order.order
     *
     * @return the value of list_show_order.order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_show_order.order
     *
     * @param order the value for list_show_order.order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public void setOrder(Integer order) {
        this.order = order;
    }
}