package edu.lcu.masterfollies.domain;

import edu.lcu.masterfollies.domain.ListShowOrder;
import edu.lcu.masterfollies.domain.ListShowOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ListShowOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int countByExample(ListShowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int deleteByExample(ListShowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int insert(ListShowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int insertSelective(ListShowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    List<ListShowOrder> selectByExample(ListShowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    ListShowOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int updateByExampleSelective(@Param("record") ListShowOrder record, @Param("example") ListShowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int updateByExample(@Param("record") ListShowOrder record, @Param("example") ListShowOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int updateByPrimaryKeySelective(ListShowOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table list_show_order
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    int updateByPrimaryKey(ListShowOrder record);
}