package edu.lcu.masterfollies.domain;

public class Questions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.question
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column questions.description
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.id
     *
     * @return the value of questions.id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.id
     *
     * @param id the value for questions.id
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.question
     *
     * @return the value of questions.question
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.question
     *
     * @param question the value for questions.question
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column questions.description
     *
     * @return the value of questions.description
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column questions.description
     *
     * @param description the value for questions.description
     *
     * @mbggenerated Mon Feb 18 11:04:41 CST 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}