package edu.lcu.masterfollies.domain;

import edu.lcu.masterfollies.domain.Rank;
import edu.lcu.masterfollies.domain.RankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int countByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int deleteByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int insert(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int insertSelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    List<Rank> selectByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    Rank selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int updateByExampleSelective(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    int updateByExample(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    int updateByPrimaryKeySelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    int updateByPrimaryKey(Rank record);
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int updateByExample(@Param("record") Rank record, @Param("example") RankExample example);
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
}