package edu.lcu.masterfollies.domain;

import edu.lcu.masterfollies.domain.Rank;
import edu.lcu.masterfollies.domain.RankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int countByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int deleteByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int insert(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int insertSelective(Rank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    List<Rank> selectByExample(RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int updateByExampleSelective(@Param("record") Rank record, @Param("example") RankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    int updateByExample(@Param("record") Rank record, @Param("example") RankExample example);
}