package edu.lcu.masterfollies.domain;

import java.io.Serializable;

public class Rank implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.judge_id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    private Integer judgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.club_id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    private Integer clubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.judge_id
     *
     * @return the value of rank.judge_id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public Integer getJudgeId() {
        return judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.judge_id
     *
     * @param judgeId the value for rank.judge_id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public void setJudgeId(Integer judgeId) {
        this.judgeId = judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.club_id
     *
     * @return the value of rank.club_id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.club_id
     *
     * @param clubId the value for rank.club_id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.rank
     *
     * @return the value of rank.rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.rank
     *
     * @param rank the value for rank.rank
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.id
     *
     * @return the value of rank.id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.id
     *
     * @param id the value for rank.id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }
}