package edu.lcu.masterfollies.domain;

<<<<<<< HEAD
public class Rank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.id
     *
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    private Integer id;

=======
import java.io.Serializable;

public class Rank implements Serializable{
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.judge_id
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    private Integer judgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.club_id
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    private Integer clubId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    private Integer rank;

    /**
<<<<<<< HEAD
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.id
     *
     * @return the value of rank.id
     *
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.id
     *
     * @param id the value for rank.id
     *
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }
=======
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rank.id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    private Integer id;
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.judge_id
     *
     * @return the value of rank.judge_id
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    public Integer getJudgeId() {
        return judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.judge_id
     *
     * @param judgeId the value for rank.judge_id
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    public void setJudgeId(Integer judgeId) {
        this.judgeId = judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.club_id
     *
     * @return the value of rank.club_id
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.club_id
     *
     * @param clubId the value for rank.club_id
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.rank
     *
     * @return the value of rank.rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.rank
     *
     * @param rank the value for rank.rank
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }
<<<<<<< HEAD
=======

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rank.id
     *
     * @return the value of rank.id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rank.id
     *
     * @param id the value for rank.id
     *
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
}