package edu.lcu.masterfollies.domain;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ResultsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int countByExample(ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int deleteByExample(ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int insert(Results record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int insertSelective(Results record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    List<Results> selectByExample(ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    Results selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByExampleSelective(@Param("record") Results record, @Param("example") ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByExample(@Param("record") Results record, @Param("example") ResultsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByPrimaryKeySelective(Results record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table results
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByPrimaryKey(Results record);
    
    List<Map<String,String>> selectResultsByJudge(@Param("judgeId")Integer judgeId, @Param("clubId") Integer clubId);
    int insertbatchResultsInsert(@Param("judgeId")Integer judgeId, @Param("clubId") Integer clubId);
}