package edu.lcu.masterfollies.domain;

import edu.lcu.masterfollies.domain.Judges;
import edu.lcu.masterfollies.domain.JudgesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JudgesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int countByExample(JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int deleteByExample(JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int insert(Judges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int insertSelective(Judges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    List<Judges> selectByExample(JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    Judges selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Judges record, @Param("example") JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int updateByExample(@Param("record") Judges record, @Param("example") JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int updateByPrimaryKeySelective(Judges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
     * @mbggenerated Fri Feb 08 09:36:39 CST 2013
     */
    int updateByPrimaryKey(Judges record);
}