package edu.lcu.masterfollies.domain;

import edu.lcu.masterfollies.domain.Judges;
import edu.lcu.masterfollies.domain.JudgesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JudgesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int countByExample(JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int deleteByExample(JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int insert(Judges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int insertSelective(Judges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    List<Judges> selectByExample(JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    Judges selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int updateByExampleSelective(@Param("record") Judges record, @Param("example") JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int updateByExample(@Param("record") Judges record, @Param("example") JudgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int updateByPrimaryKeySelective(Judges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judges
     *
<<<<<<< HEAD
     * @mbggenerated Thu Feb 07 16:47:55 CST 2013
=======
     * @mbggenerated Tue Feb 05 11:54:28 CST 2013
>>>>>>> 8878c4e4ca54b13003c87e3e558b1088325d36d1
     */
    int updateByPrimaryKey(Judges record);
}