package edu.lcu.masterfollies.domain;

public class Judges {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.id
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.first_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.last_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.user_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.password
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.is_super
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    private Boolean isSuper;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.id
     *
     * @return the value of judges.id
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.id
     *
     * @param id the value for judges.id
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.first_name
     *
     * @return the value of judges.first_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.first_name
     *
     * @param firstName the value for judges.first_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.last_name
     *
     * @return the value of judges.last_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.last_name
     *
     * @param lastName the value for judges.last_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.user_name
     *
     * @return the value of judges.user_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.user_name
     *
     * @param userName the value for judges.user_name
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.password
     *
     * @return the value of judges.password
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.password
     *
     * @param password the value for judges.password
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.is_super
     *
     * @return the value of judges.is_super
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public Boolean getIsSuper() {
        return isSuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.is_super
     *
     * @param isSuper the value for judges.is_super
     *
     * @mbggenerated Mon Feb 04 19:26:47 CST 2013
     */
    public void setIsSuper(Boolean isSuper) {
        this.isSuper = isSuper;
    }
}