package edu.lcu.masterfollies.domain;

public class Details {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.id
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.detail_description
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    private String detailDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.id
     *
     * @return the value of details.id
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.id
     *
     * @param id the value for details.id
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.detail_description
     *
     * @return the value of details.detail_description
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    public String getDetailDescription() {
        return detailDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.detail_description
     *
     * @param detailDescription the value for details.detail_description
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    public void setDetailDescription(String detailDescription) {
        this.detailDescription = detailDescription == null ? null : detailDescription.trim();
    }
}