package edu.lcu.masterfollies.domain;

import edu.lcu.masterfollies.domain.Details;
import edu.lcu.masterfollies.domain.DetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int countByExample(DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int deleteByExample(DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int insert(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int insertSelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    List<Details> selectByExample(DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    Details selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByExampleSelective(@Param("record") Details record, @Param("example") DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByExample(@Param("record") Details record, @Param("example") DetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByPrimaryKeySelective(Details record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbggenerated Thu Jan 17 19:19:16 CST 2013
     */
    int updateByPrimaryKey(Details record);
}