package edu.lcu.masterfollies.domain;

public class Judges {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.ID
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.FirstName
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.LastName
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.Username
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judges.Password
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.ID
     *
     * @return the value of judges.ID
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.ID
     *
     * @param id the value for judges.ID
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.FirstName
     *
     * @return the value of judges.FirstName
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.FirstName
     *
     * @param firstname the value for judges.FirstName
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.LastName
     *
     * @return the value of judges.LastName
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.LastName
     *
     * @param lastname the value for judges.LastName
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.Username
     *
     * @return the value of judges.Username
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.Username
     *
     * @param username the value for judges.Username
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judges.Password
     *
     * @return the value of judges.Password
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judges.Password
     *
     * @param password the value for judges.Password
     *
     * @mbggenerated Tue Jan 15 15:41:21 CST 2013
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}